color0 #1c1c1c
color1 #8b1a4a
color2 #c9b8e8
color3 #9d7fd4
color4 #b8a8e0
color5 #6a4aad
color6 #8860c8
color7 #f0eefa
color8 #505050
color9 #6a0030
color10 #ede8fa
color11 #c9b8e8
color12 #e8e0fa
color13 #9d7fd4
color14 #b090e0
color15 #ffffff

cursor                #b060e0
cursor_text_color     #070707
background            #070707
foreground            #f0eefa
selection_foreground  #070707
selection_background  #9d7fd4
active_border_color   #c9b8e8
inactive_border_color #141414
url_color             #c9b8e8

active_tab_foreground   #070707
active_tab_background   #c9b8e8
inactive_tab_foreground #f0eefa
inactive_tab_background #141414
cursor_trail_color      #f0eefa
