color0 #1c1c1c
color1 #d4431a
color2 #f2b870
color3 #f5ce8a
color4 #8bbfd6
color5 #6a9ab8
color6 #a8d4e6
color7 #faf0e4
color8 #505050
color9 #e03a1a
color10 #f7ddb0
color11 #f2b870
color12 #bdd9e8
color13 #8bbfd6
color14 #c4e4f0
color15 #ffffff

cursor                #f2b870
cursor_text_color     #070707
background            #070707
foreground            #faf0e4
selection_foreground  #070707
selection_background  #8bbfd6
active_border_color   #f2b870
inactive_border_color #141414
url_color             #f2b870

active_tab_foreground   #070707
active_tab_background   #f2b870
inactive_tab_foreground #faf0e4
inactive_tab_background #141414
cursor_trail_color      #faf0e4
