-- Generated by Noctalia

local primary = "rgb(ebbcba)"
local surface = "rgb(191724)"
local secondary = "rgb(9ccfd8)"
local error = "rgb(eb6f92)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
