-- Generated by Noctalia

local primary = "rgb(f2b870)"
local surface = "rgb(070707)"
local secondary = "rgb(8bbfd6)"
local error = "rgb(d4431a)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
