[bar]
order = [ "uwu" ]

    [bar.uwu]
    background_opacity = 0.9499999787658453
    border = "surface"
    end = [ "tray", "notifications", "media" ]
    font_weight = 400
    margin_ends = 100
    padding = 15
    radius = 20
    scale = 1.350000012665987
    start = [ "workspaces", "active_window" ]
    thickness = 40

[desktop_widgets]
enabled = false

[keybinds]
down = [ "Ctrl+j" ]
left = [ "Ctrl+h" ]
right = [ "Ctrl+l" ]
up = [ "Ctrl+k" ]

[notification]
offset_x = 10.0
offset_y = 10.0
scale = 0.7500000037252903

[osd]
scale = 0.7500000037252903

[shell]
avatar_path = "/home/ferret/Downloads/76d2ed7cc08e67529469189cbd81d516.webp"
clipboard_auto_paste = "off"
clipboard_history_max_entries = 100.0
corner_radius_scale = 0.5000000074505806
date_format = "{:%A}, {:/%d/%m/%Y}"
font_family = "CaskaydiaCove NFM"
lang = "en"
polkit_agent = true
settings_show_advanced = true
show_location = false
ui_scale = 1.25

    [shell.panel]
    launcher_categories = false
    launcher_placement = "attached"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Lavender"
custom_palette = "UwU"
source = "custom"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "ghostty", "hyprland", "qt", "starship" ]
    community_ids = [ "yazi", "discord" ]

[wallpaper]
directory = "/home/ferret/Pictures/bg"
transition = [ "fade" ]

    [wallpaper.default]
    path = "/home/ferret/Pictures/bg/17515911809700.png"

    [wallpaper.last]
    path = "/home/ferret/Pictures/bg/17515911809700.png"

    [wallpaper.monitors.DP-1]
    path = "/home/ferret/Pictures/bg/17515911809700.png"

    [wallpaper.monitors.DP-2]
    path = "/home/ferret/Pictures/bg/17515911809700.png"

    [[wallpaper.favorite]]
    path = "/home/ferret/Pictures/bg/17515911809700.png"
    theme_mode = "auto"

[weather]
address = "Uhersky Brod, Czech Republic"

[widget.active_window]
max_length = 450

[widget.clock]
format = "{:%H:%M} {:/%d/%m/%Y}"

[widget.media]
max_length = 450.0
title_scroll = "on_hover"

[widget.workspaces]
empty_color = "outline"
focused_color = "secondary"
minimal = true
occupied_color = "outline"
scale = 1.1500000000000001