[theme.templates]
enable_builtin_templates   = true
enable_community_templates = true
builtin_ids                = []
community_ids              = []

[theme.templates.colloid-icons]
input_path = "~/.config/noctalia/templates/icons.cfg"
output_path = "~/.config/noctalia/mots/etc/colloid-noctalia.conf"
post_hook = "sh ~/.config/noctalia/mots/bin/dynamic_icons.sh"
